/* Generated By:JavaCC: Do not edit this line. SqlFormatterConstants.java */
package edu.wustl.common.util;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlFormatterConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 1;
  /** RegularExpression Id. */
  int FROM = 2;
  /** RegularExpression Id. */
  int INJOIN = 3;
  /** RegularExpression Id. */
  int LJOIN = 4;
  /** RegularExpression Id. */
  int WHERE = 5;
  /** RegularExpression Id. */
  int ON = 6;
  /** RegularExpression Id. */
  int ANY = 7;
  /** RegularExpression Id. */
  int _SELECT11 = 8;
  /** RegularExpression Id. */
  int _ANY1 = 9;
  /** RegularExpression Id. */
  int _FROM1 = 13;
  /** RegularExpression Id. */
  int _ANY2 = 14;
  /** RegularExpression Id. */
  int _INJOIN1 = 15;
  /** RegularExpression Id. */
  int _LJOIN1 = 16;
  /** RegularExpression Id. */
  int _WHERE1 = 17;
  /** RegularExpression Id. */
  int _ANY3 = 20;
  /** RegularExpression Id. */
  int _ON1 = 22;
  /** RegularExpression Id. */
  int _ANY4 = 23;
  /** RegularExpression Id. */
  int _ON2 = 26;
  /** RegularExpression Id. */
  int _ANY5 = 27;
  /** RegularExpression Id. */
  int _INJOIN2 = 28;
  /** RegularExpression Id. */
  int _LJOIN2 = 29;
  /** RegularExpression Id. */
  int _WHERE2 = 30;
  /** RegularExpression Id. */
  int _ANY6 = 33;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SELECT_ST = 1;
  /** Lexical state. */
  int FROM_ST = 2;
  /** Lexical state. */
  int JOIN_ST = 3;
  /** Lexical state. */
  int ON_ST = 4;
  /** Lexical state. */
  int WHERE_ST = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"select \"",
    "\" from \"",
    "\" inner join \"",
    "\" left join \"",
    "\" where \"",
    "\" on \"",
    "<ANY>",
    "<_SELECT11>",
    "<_ANY1>",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<_FROM1>",
    "<_ANY2>",
    "<_INJOIN1>",
    "<_LJOIN1>",
    "<_WHERE1>",
    "\"(\"",
    "\")\"",
    "<_ANY3>",
    "\"(\"",
    "<_ON1>",
    "<_ANY4>",
    "\"(\"",
    "\")\"",
    "<_ON2>",
    "<_ANY5>",
    "<_INJOIN2>",
    "<_LJOIN2>",
    "<_WHERE2>",
    "\"(\"",
    "\")\"",
    "<_ANY6>",
  };

}
