--  DROP TABLES 
DROP TABLE IF EXISTS CAB2B_UPGRADE ;


--  CREATE TABLES 
CREATE TABLE CAB2B_UPGRADE ( 
	ID BIGINT COMMENT 'SYSTEM GENERATED PRIMARY KEY.',
	NAME VARCHAR(200),			
	PRIMARY KEY (ID)
)ENGINE=INNODB 
;
