/*
 * FiltersViewConsole.java
 *
 * Created on December 14, 2007, 2:16 PM
 */

package edu.wustl.cab2b.client.ui.controls.sheet;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

import javax.swing.table.AbstractTableModel;

/**
 
 @author  jasbir_sachdeva
 */
public class FiltersViewConsole extends javax.swing.JPanel {

    SheetCustomizationModel scm;

    ConsolidatedFilterViewTblModel viewTableModel = new ConsolidatedFilterViewTblModel();

    ChangesListener filterListener = new ChangesListener();

    /** Creates new form FiltersViewConsole */
    public FiltersViewConsole() {
        initComponents();
    }

    void setModel(SheetCustomizationModel scm) {
        if (null != this.scm)
            this.scm.removePropertyChangeListener(filterListener);
        this.scm = scm;
        tblFiltersView.setModel(viewTableModel);
        scm.addPropertyChangeListener(filterListener);
    }

    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiltersView = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        tblFiltersView.setFillsViewportHeight(true);
        tblFiltersView.setGridColor(new java.awt.Color(255, 255, 255));
        tblFiltersView.setShowHorizontalLines(false);
        tblFiltersView.setShowVerticalLines(false);
        tblFiltersView.getTableHeader().setResizingAllowed(false);
        tblFiltersView.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblFiltersView);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;

    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTable tblFiltersView;

    // End of variables declaration//GEN-END:variables

    class ConsolidatedFilterViewTblModel extends AbstractTableModel {

        public int getRowCount() {
            return scm.getActiveFiltersCount();
        }

        public int getColumnCount() {
            return 1;
        }

        @Override
        public String getColumnName(int columnIndex) {
            return "";
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return String.class;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            SheetColumn colSheet = scm.getActiveSheetColumnAt(rowIndex);
            ColumnFilterModel cfm = colSheet.getFilterCondition();
            return colSheet.getHeaderValue() + ": " + cfm.getFilterDescription();
        }

    }

    class ChangesListener implements PropertyChangeListener {

        public void propertyChange(PropertyChangeEvent evt) {
            viewTableModel.fireTableDataChanged();
        }

    }

}
